package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ws/workspace/jdk-8u275/label/windows-x86_64/type/b8/build/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, November 5, 2020 3:58:40 AM PST
*/


/** Server callback API, passed to Activator in active method.
    */
public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
