package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ws/workspace/jdk-8u275/label/windows-x86_64/type/b8/build/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, November 5, 2020 3:58:40 AM PST
*/

public interface IIOP_CLEAR_TEXT
{

  /** Possible values for endpointType argument on Server.getEndpoint()
    * If you change the value of this constant then update
    * core.EndPoint accordingly.  It has a duplicate definition
    * to avoid a compilation dependency.
    */
  public static final String value = "IIOP_CLEAR_TEXT";
}
