package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ws/workspace/jdk-8u275/label/windows-x86_64/type/b8/build/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, November 5, 2020 3:58:41 AM PST
*/

public interface LIFESPAN_POLICY_ID
{

  /**
	 * The value representing LIFESPAN_POLICY_ID.
	 */
  public static final int value = (int)(17L);
}
